DROP DATABASE IF EXISTS testDB;

CREATE DATABASE testDB;

USE testDB;

CREATE TABLE testData (
    id INT UNSIGNED AUTO_INCREMENT,
    lName VARCHAR(50) NOT NULL,
    fName VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    password VARCHAR(50) NOT NULL,
    CONSTRAINT pk_testData PRIMARY KEY (id)
);